### PR TITLE
Implement Notifications w/ Firebase Messaging

### PR DESCRIPTION
**Pull request by dishanest**
## Overview

Implement push notifications using Firebase Cloud Messaging.

## Changes Made
- add pod 'Firebase/Messaging'
- implement messaging delegate functions in `Notifications`
- replace instances of `deviceToken` with `fcmToken` in `UserData` 

## Test Coverage
- Sent test notification from Firebase console
- Manually pinged test notification from backend
- Ensured `createUser` still works on simulator

## Next Steps
- Merge this PR w/ release branch to test notifs in prod environment

## Screenshots

<details>

  <summary>Test Notification from Firebase Console</summary>

</details>

<details>

  <summary>Test Notification from volume-backend</summary>

</details>

### CODE REVIEW

**Review by amyqxhuang — APPROVED** [review]
looks good to me!

**Review by Npikielny — APPROVED** [review]
Looks good!

**Review by NgaiJustin — APPROVED** [review]
Looks good, but curious what motivated this change since this might add to the costs to maintain? Also, how does this affect the use of the simulator.

**Comment by dishanest** [comment]
@NgaiJustin 
> Looks good, but curious what motivated this change since this might add to the costs to maintain? Also, how does this affect the use of the simulator.

FCM is free, as far as my understanding goes: https://firebase.google.com/products/cloud-messaging

The simulator of course still can't receive notifications, and the FCM won't activate, but the `createUser` mutation will still work with the fake dev FCM token & return a usable UUID.

**Pull request merged**
